version: '3'

services:
  api:
    build:
      context: .
    container_name: user.account
    ports:
     - 10080:10080
    environment:
      - Database__ConnectionString=mongodb://foo:bar@mongo:27017
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo'
    expose:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=foo
      - MONGO_INITDB_ROOT_PASSWORD=bar